var articleDetails_tweet = {
    "message":"Entity Details populated Successfully...", "data":{
        "orderedList":["TW:204846789466140673"], "sections":[
            {"type":"TWEETS", "title":"FirstTweets", "isVisible":true, "baseResults":["TW:204846789466140673"], "relatedResults":[], "last":0, "hasMore":false}
        ], "results":[
            {"id":"TW:204846789466140673", "itemId":0, "type":"TWEETS", "title":"Apple, Samsung kick off patent talks: US District Judge Lucy Koh had ordered Apple Inc and Samsung Electronics C... <span class='lightGrey'><a target='_blank' href='http://t.co/Nu584doT'>http://t.co/Nu584doT</a></span>", "url":"http://businesstoday.intoday.in/story/apple-vs-samsung-patent-infringement-allegations/1/184709.html", "timestamp":"Tue, 22 May 2012 01:10:00 -0700", "isBookmarked":false, "extra":{"description":"Island-Based (St. Kitts) Technology Consultant, Entrepreneur, Spiritual Geek - Apple Certified Support Professional (ACSP)", "date":1337674200000, "name":"Lenford C. Lloyd", "screenName":"LenfordCLloyd", "coreTweet":"Apple, Samsung kick off patent talks: US District Judge Lucy Koh had ordered Apple Inc and Samsung Electronics C", "userImage":"http://a0.twimg.com/profile_images/1268715592/images_normal.jpg", "entity":{"name":"Samsung Electronics Co., Ltd.", "id":"C:282003", "searchToken":"C:SamsungElectronicsCoLtd", "ticker":"A005930.KOSE"}, "document":{"id":"D:531322369", "itemId":0, "type":"DOCUMENT", "title":"Apple, Samsung kick off patent talks", "url":"http://businesstoday.intoday.in/story/apple-vs-samsung-patent-infringement-allegations/1/184709.html", "source":"Business Today", "timestamp":"Tue, 22 May 2012 04:27:45 -0700", "isBookmarked":false, "image":"http://10.10.10.45/imagerepository/1/506/66/f5/66f5e140-a404-11e1-aba7-0019b9cc211d.jpg", "favicon":"http://10.10.10.45/imagerepository/3/497/e2/27/e227cef0-9d5b-11e1-82ed-0019b9cc211d.ico", "summary":"US District Judge Lucy Koh had ordered Apple Inc and Samsung Electronics Co to participate in a two-day mediation session to settle Apple's claims that the Korean maker's smartphones and Galaxy line of tablet computers violated its patent and trademark. Apple had sued Samsung over the  alleged patent infringement last April .", "extra":{"matchedContentTypes":[
                {"name":"News and Web", "id":"C:500840", "searchToken":"F:NewsandWeb"}
            ], "groupId":320115250, "accessType":0}, "matchedCompanies":[
                {"id":"C:254739", "title":"Apple Inc.", "url":"C:AppleInc"},
                {"id":"C:282003", "title":"Samsung Electronics Co., Ltd.", "url":"C:SamsungElectronicsCoLtd"},
                {"id":"C:254807", "title":"Samsung Group", "url":"C:SamsungGroup"},
                {"id":"C:725103", "title":"Motorola Mobility Holdings, Inc.", "url":"C:MotorolaMobilityHoldingsInc"}
            ], "matchedTopics":[
                {"id":"C:296554", "title":"Notebook & Tablet Personal Computer (PC) Market", "url":"T:NotebookTabletPersonalComputerPCMarket"}
            ], "quoteList":[
                {"text":" FROM THE MAGAZINE:   Samsung knocks the wind out of Nokia   In the official biography of Steve Jobs, the  late Apple co-founder  told author Walter Isaacson that \"I'm going to destroy Android, because it's a stolen product. I'm willing to go thermonuclear war on this.\" <b>\"I will spend my last dying breath if I need to and I will spend every penny of Apple's $40 billion in the bank, to right this wrong,\"</b>  according to the biography. - With agency inputs   MORE FROM  Corporate LATEST HEADLINES Advertisement FROM THE MAGAZINE MOST POPULAR Stories Photos       India's Best B schools   The BT-Nielsen ranking is popular among MBA aspirants, institutes and HR managers alike.   Best companies to work for in India   This annual Indicus Analytics survey ranks the best firms to work for in India.    ", "person":""},
                {"text":" MUST READ:   US sues Apple over e-book pricing   Besides Samsung, Apple has also been filing suits against other manufacturers like HTC and Motorola Mobility, which are actually proxies for Apple products' major competitor Android, the operating system Google gives away to device makers. FROM THE MAGAZINE:   Samsung knocks the wind out of Nokia   In the official biography of Steve Jobs, the  late Apple co-founder  told author Walter Isaacson that <b>\"I'm going to destroy Android, because it's a stolen product. I'm willing to go thermonuclear war on this.\"</b>  \"I will spend my last dying breath if I need to and I will spend every penny of Apple's $40 billion in the bank, to right this wrong,\" according to the biography. - With agency inputs   MORE FROM  Corporate LATEST HEADLINES Advertisement FROM THE MAGAZINE MOST POPULAR Stories Photos       India's Best B schools   The BT-Nielsen ranking is popular among MBA aspirants, institutes and HR managers alike.    ", "person":""}
            ]}, "relatedDocs":[
                {"id":"D:531174224", "itemId":0, "type":"DOCUMENT", "title":"Lawyers: Apple, Samsung unlikely to make peace in court-ordered talks", "url":"http://www.macnews.com/2012/05/21/lawyers-apple-samsung-unlikely-make-peace-court-ordered-talks", "source":"MacMinute", "timestamp":"Mon, 21 May 2012 14:04:06 -0700", "isBookmarked":false, "favicon":"http://10.10.10.45/imagerepository/3/497/d0/63/d0635840-9d58-11e1-82ed-0019b9cc211d.ico", "extra":{"matchedContentTypes":[
                    {"name":"Industry Sources", "id":"C:288557", "searchToken":"F:IndustrySources"},
                    {"name":"News and Web", "id":"C:500840", "searchToken":"F:NewsandWeb"}
                ], "groupId":319992189, "accessType":0}},
                {"id":"D:530967072", "itemId":0, "type":"DOCUMENT", "title":"Apple, Samsung Ordered Into Patent Settlement Conference", "url":"http://www.bloomberg.com/news/2012-05-21/apple-samsung-ordered-into-patent-settlement-conference.html", "source":"Bloomberg.com", "timestamp":"Sun, 20 May 2012 21:29:43 -0700", "isBookmarked":false, "image":"http://10.10.10.45/imagerepository/1/498/87/f1/87f15d20-9e50-11e1-82ed-0019b9cc211d.jpg", "favicon":"http://10.10.10.45/imagerepository/3/497/f7/12/f712b2f0-9d5e-11e1-82ed-0019b9cc211d.ico", "extra":{"matchedContentTypes":[
                    {"name":"News Wires", "id":"C:276205", "searchToken":"F:NewsWires"}
                ], "groupId":319820930, "accessType":0}}
            ], "groupImage":"http://10.10.10.134:9988/FRMobileService/images/Clusters_02.png", "profileUrl":"https://twitter.com/#!/LenfordCLloyd", "tinyUrl":"http://t.co/Nu584doT", "tweetUrl":"https://twitter.com/#!/LenfordCLloyd/status/204846789466140673", "notableDetails":[
                {"userImage":"http://a0.twimg.com/sticky/default_profile_images/default_profile_4_normal.png", "screenName":"BussinessTree", "itemId":0, "clipped":false, "profileUrl":"https://twitter.com/#!/BussinessTree"},
                {"userImage":"http://a0.twimg.com/profile_images/1318080099/PhoenixBird_normal.jpg", "screenName":"KBurnNotice", "itemId":0, "clipped":false, "profileUrl":"https://twitter.com/#!/KBurnNotice"}
            ], "timeLabel":"22-May-2012"}}
        ]
    },
    "status":"SUCCESS"
}