var monitorEvents = {"message":"Monitor Results populated Successfully.",
    "data":{"sections":[
        {"type":"EVENTS",
            "title":"Stock & Financial Events",
            "isVisible":true,
            "baseResults":["E:18063085",
                "E:18063330",
                "E:17933990",
                "E:17900586",
                "E:17888553",
                "E:17889879",
                "E:17873439",
                "E:17772142",
                "E:17766395",
                "E:17709298",
                "E:17710304",
                "E:17640307",
                "E:17614732",
                "E:17595017",
                "E:17583219",
                "E:17583952",
                "E:17497030",
                "E:17426677",
                "E:17344382",
                "E:17217919",
                "E:17221746",
                "E:17204320",
                "E:17148671",
                "E:17149095",
                "E:17090432",
                "E:16946413",
                "E:16946511",
                "E:16892790"],
            "relatedResults":[],
            "last":28,
            "hasMore":false}
    ],
        "results":[
            {"id":"E:18063085",
                "itemId":0,
                "type":"EVENT",
                "title":"<span class='colorOrange'>HDFC Bank Limited</span><br/>Stock closing price <span class='bold'>($31.78) <span class='colorRed'>DROPPED BELOW</span> 100-day Moving Average</span> ($31.92)",
                "timestamp":"Tue, 8 May 2012 00:00:00 -0700",
                "isBookmarked":false,
                "extra":{"eventType":302}},
            {"id":"E:18063330",
                "itemId":0,
                "type":"EVENT",
                "title":"<span class='colorOrange'>HDFC Bank Limited</span><br/>Stock closing price <span class='bold'>($31.78) <span class='colorRed'>DROPPED BELOW</span> 200-day Moving Average</span> ($32.11)",
                "timestamp":"Tue, 8 May 2012 00:00:00 -0700",
                "isBookmarked":false,
                "extra":{"eventType":303}},
            {"id":"E:17933990",
                "itemId":0,
                "type":"EVENT",
                "title":"<span class='colorOrange'>HDFC Bank Limited</span><br/>Stock closing price <span class='bold'>($33.44) <span class='colorRed'>DROPPED BELOW</span> 50-day Moving Average</span> ($34.08)",
                "timestamp":"Mon, 23 Apr 2012 00:00:00 -0700",
                "isBookmarked":false,
                "extra":{"eventType":301}},
            {"id":"E:17900586",
                "itemId":0,
                "type":"EVENT",
                "title":"<span class='colorOrange'>HDFC Bank Limited</span><br/>Stock closing price <span class='bold'>($34.03) <span class='colorRed'>DROPPED BELOW</span> 50-day Moving Average</span> ($34.04)",
                "timestamp":"Wed, 18 Apr 2012 00:00:00 -0700",
                "isBookmarked":false,
                "extra":{"eventType":301}},
            {"id":"E:17888553",
                "itemId":0,
                "type":"EVENT",
                "title":"<span class='colorOrange'>HDFC Bank Limited</span><br/>Stock closing price <span class='bold'>($34.84) <span class='colorGreen'>ROSE ABOVE</span> 50-day Moving Average</span> ($34.03)",
                "timestamp":"Tue, 17 Apr 2012 00:00:00 -0700",
                "isBookmarked":false,
                "extra":{"eventType":301}},
            {"id":"E:17889879",
                "itemId":0,
                "type":"EVENT",
                "title":"<span class='colorOrange'>HDFC Bank Limited</span><br/>Stock price <span class='bold'><span class='colorGreen'> CLOSED UP +5.13%</span></span> at $34.84",
                "timestamp":"Tue, 17 Apr 2012 00:00:00 -0700",
                "isBookmarked":false,
                "extra":{"eventType":300}},
            {"id":"E:17873439",
                "itemId":0,
                "type":"EVENT",
                "title":"<span class='colorOrange'>HDFC Bank Limited</span><br/>Stock closing price <span class='bold'>($33.10) <span class='colorRed'>DROPPED BELOW</span> 50-day Moving Average</span> ($33.95)",
                "timestamp":"Fri, 13 Apr 2012 00:00:00 -0700",
                "isBookmarked":false,
                "extra":{"eventType":301}},
            {"id":"E:17772142",
                "itemId":0,
                "type":"EVENT",
                "title":"<span class='colorOrange'>HDFC Bank Limited</span><br/>Stock closing price <span class='bold'>($34.10) <span class='colorGreen'>ROSE ABOVE</span> 50-day Moving Average</span> ($33.43)",
                "timestamp":"Fri, 30 Mar 2012 00:00:00 -0700",
                "isBookmarked":false,
                "extra":{"eventType":301}},
            {"id":"E:17766395",
                "itemId":0,
                "type":"EVENT",
                "title":"<span class='colorOrange'>HDFC Bank Limited</span><br/>Stock closing price <span class='bold'>($33.17) <span class='colorRed'>DROPPED BELOW</span> 50-day Moving Average</span> ($33.33)",
                "timestamp":"Thu, 29 Mar 2012 00:00:00 -0700",
                "isBookmarked":false,
                "extra":{"eventType":301}},
            {"id":"E:17709298",
                "itemId":0,
                "type":"EVENT",
                "title":"<span class='colorOrange'>ICICI Bank Limited</span><br/>Stock closing price <span class='bold'>($35.62) <span class='colorRed'>DROPPED BELOW</span> 50-day Moving Average</span> ($36.02)",
                "timestamp":"Thu, 22 Mar 2012 00:00:00 -0700",
                "isBookmarked":false,
                "extra":{"eventType":301}},
            {"id":"E:17710304",
                "itemId":0,
                "type":"EVENT",
                "title":"<span class='colorOrange'>HDFC Bank Limited</span><br/>Stock closing price <span class='bold'>($32.85) <span class='colorRed'>DROPPED BELOW</span> 200-day Moving Average</span> ($32.88)",
                "timestamp":"Thu, 22 Mar 2012 00:00:00 -0700",
                "isBookmarked":false,
                "extra":{"eventType":303}},
            {"id":"E:17640307",
                "itemId":0,
                "type":"EVENT",
                "title":"<span class='colorOrange'>ICICI Bank Limited</span><br/>Stock closing price <span class='bold'>($38.08) <span class='colorGreen'>ROSE ABOVE</span> 200-day Moving Average</span> ($37.43)",
                "timestamp":"Tue, 13 Mar 2012 00:00:00 -0700",
                "isBookmarked":false,
                "extra":{"eventType":303}},
            {"id":"E:17614732",
                "itemId":0,
                "type":"EVENT",
                "title":"<span class='colorOrange'>ICICI Bank Limited</span><br/>Stock price <span class='bold'><span class='colorGreen'> CLOSED UP +5.33%</span></span> at $37.14",
                "timestamp":"Fri, 9 Mar 2012 00:00:00 -0800",
                "isBookmarked":false,
                "extra":{"eventType":300}},
            {"id":"E:17595017",
                "itemId":0,
                "type":"EVENT",
                "title":"<span class='colorOrange'>ICICI Bank Limited</span><br/>Stock closing price <span class='bold'>($34.69) <span class='colorGreen'>ROSE ABOVE</span> 50-day Moving Average</span> ($33.96)",
                "timestamp":"Wed, 7 Mar 2012 00:00:00 -0800",
                "isBookmarked":false,
                "extra":{"eventType":301}},
            {"id":"E:17583219",
                "itemId":0,
                "type":"EVENT",
                "title":"<span class='colorOrange'>ICICI Bank Limited</span><br/>Stock price <span class='bold'><span class='colorRed'>CLOSED DOWN -5.09%</span></span> at $33.77",
                "timestamp":"Tue, 6 Mar 2012 00:00:00 -0800",
                "isBookmarked":false,
                "extra":{"eventType":300}},
            {"id":"E:17583952",
                "itemId":0,
                "type":"EVENT",
                "title":"<span class='colorOrange'>ICICI Bank Limited</span><br/>Stock closing price <span class='bold'>($33.77) <span class='colorRed'>DROPPED BELOW</span> 50-day Moving Average</span> ($33.79)",
                "timestamp":"Tue, 6 Mar 2012 00:00:00 -0800",
                "isBookmarked":false,
                "extra":{"eventType":301}},
            {"id":"E:17497030",
                "itemId":0,
                "type":"EVENT",
                "title":"<span class='colorOrange'>ICICI Bank Limited</span><br/>Stock closing price <span class='bold'>($37.51) <span class='colorRed'>DROPPED BELOW</span> 200-day Moving Average</span> ($38.10)",
                "timestamp":"Thu, 23 Feb 2012 00:00:00 -0800",
                "isBookmarked":false,
                "extra":{"eventType":303}},
            {"id":"E:17426677",
                "itemId":0,
                "type":"EVENT",
                "title":"<span class='colorOrange'>ICICI Bank Limited</span><br/>Stock closing price <span class='bold'>($38.96) <span class='colorGreen'>ROSE ABOVE</span> 200-day Moving Average</span> ($38.31)",
                "timestamp":"Wed, 15 Feb 2012 00:00:00 -0800",
                "isBookmarked":false,
                "extra":{"eventType":303}},
            {"id":"E:17344382",
                "itemId":0,
                "type":"EVENT",
                "title":"<span class='colorOrange'>HDFC Bank Limited</span><br/>Stock closing price <span class='bold'>($33.52) <span class='colorGreen'>ROSE ABOVE</span> 200-day Moving Average</span> ($32.66)",
                "timestamp":"Fri, 3 Feb 2012 00:00:00 -0800",
                "isBookmarked":false,
                "extra":{"eventType":303}},
            {"id":"E:17217919",
                "itemId":0,
                "type":"EVENT",
                "title":"<span class='colorOrange'>ICICI Bank Limited</span><br/>Stock closing price <span class='bold'>($32.85) <span class='colorGreen'>ROSE ABOVE</span> 100-day Moving Average</span> ($32.68)",
                "timestamp":"Thu, 19 Jan 2012 00:00:00 -0800",
                "isBookmarked":false,
                "extra":{"eventType":302}},
            {"id":"E:17221746",
                "itemId":0,
                "type":"EVENT",
                "title":"<span class='colorOrange'>ICICI Bank Limited</span><br/>Stock price <span class='bold'><span class='colorGreen'> CLOSED UP +5.22%</span></span> at $32.85",
                "timestamp":"Thu, 19 Jan 2012 00:00:00 -0800",
                "isBookmarked":false,
                "extra":{"eventType":300}},
            {"id":"E:17204320",
                "itemId":0,
                "type":"EVENT",
                "title":"<span class='colorOrange'>HDFC Bank Limited</span><br/>Stock closing price <span class='bold'>($29.37) <span class='colorGreen'>ROSE ABOVE</span> 100-day Moving Average</span> ($29.31)",
                "timestamp":"Wed, 18 Jan 2012 00:00:00 -0800",
                "isBookmarked":false,
                "extra":{"eventType":302}},
            {"id":"E:17148671",
                "itemId":0,
                "type":"EVENT",
                "title":"<span class='colorOrange'>ICICI Bank Limited</span><br/>Stock closing price <span class='bold'>($29.95) <span class='colorGreen'>ROSE ABOVE</span> 50-day Moving Average</span> ($29.89)",
                "timestamp":"Tue, 10 Jan 2012 00:00:00 -0800",
                "isBookmarked":false,
                "extra":{"eventType":301}},
            {"id":"E:17149095",
                "itemId":0,
                "type":"EVENT",
                "title":"<span class='colorOrange'>ICICI Bank Limited</span><br/>Stock price <span class='bold'><span class='colorGreen'> CLOSED UP +6.06%</span></span> at $29.95",
                "timestamp":"Tue, 10 Jan 2012 00:00:00 -0800",
                "isBookmarked":false,
                "extra":{"eventType":300}},
            {"id":"E:17090432",
                "itemId":0,
                "type":"EVENT",
                "title":"<span class='colorOrange'>ICICI Bank Limited</span><br/>Stock price <span class='bold'><span class='colorGreen'> CLOSED UP +6.51%</span></span> at $28.15",
                "timestamp":"Tue, 3 Jan 2012 00:00:00 -0800",
                "isBookmarked":false,
                "extra":{"eventType":300}},
            {"id":"E:16946413",
                "itemId":0,
                "type":"EVENT",
                "title":"<span class='colorOrange'>ICICI Bank Limited</span><br/>Stock price <span class='bold'><span class='colorRed'>CLOSED DOWN -7.13%</span></span> at $26.31",
                "timestamp":"Mon, 12 Dec 2011 00:00:00 -0800",
                "isBookmarked":false,
                "extra":{"eventType":300}},
            {"id":"E:16946511",
                "itemId":0,
                "type":"EVENT",
                "title":"<span class='colorOrange'>HDFC Bank Limited</span><br/>Stock price <span class='bold'><span class='colorRed'>CLOSED DOWN -5.24%</span></span> at $26.78",
                "timestamp":"Mon, 12 Dec 2011 00:00:00 -0800",
                "isBookmarked":false,
                "extra":{"eventType":300}},
            {"id":"E:16892790",
                "itemId":0,
                "type":"EVENT",
                "title":"<span class='colorOrange'>ICICI Bank Limited</span><br/>Stock price <span class='bold'><span class='colorRed'>CLOSED DOWN -5.57%</span></span> at $28.33",
                "timestamp":"Thu, 8 Dec 2011 00:00:00 -0800",
                "isBookmarked":false,
                "extra":{"eventType":300}}
        ],
        "monitor":{"id":"M:67657",
            "type":"PRIVATE",
            "title":"Indian Banks",
            "timestamp":"Mon, 26 Dec 2011 01:28:43 -0800",
            "hasNew":false,
            "hasNewMail":false,
            "hasMail":true,
            "hasChart":true,
            "favorite":false,
            "isAdmin":false}},
    "status":"SUCCESS"}