var monitorDetailsMT = {"message":"Monitor Results populated Successfully.",
    "data":{"sections":[
        {"type":"MANAGEMENT_TURNOVER",
            "title":"Management Changes",
            "isVisible":true,
            "baseResults":["MT:18186317",
                "MT:18139454",
                "MT:18139460",
                "MT:17992325",
                "MT:17797282",
                "MT:17065028",
                "MT:17787649",
                "MT:17708938",
                "MT:17690367",
                "MT:17629639",
                "MT:17629787",
                "MT:17065020",
                "MT:17065029",
                "MT:17558400",
                "MT:17558487",
                "MT:17558489",
                "MT:17593395",
                "MT:17065030",
                "MT:17519067",
                "MT:17519098",
                "MT:17360953",
                "MT:17204022",
                "MT:17312937",
                "MT:17230180",
                "MT:17065023",
                "MT:17065067",
                "MT:17065068",
                "MT:17085959",
                "MT:17086015",
                "MT:17078725"],
            "relatedResults":[],
            "last":30,
            "hasMore":false}
    ],
        "results":[
            {"id":"MT:18186317",
                "itemId":0,
                "type":"MT",
                "title":"<span class='colorOrange'>IndusInd Bank Ltd</span><br/><span class='bold'>RS Sharma</span> <span class='bold'><span class='colorGreen'>JOINED</span></span> as Board of Directors",
                "timestamp":"Wed, 23 May 2012 00:00:00 -0700",
                "isBookmarked":false},
            {"id":"MT:18139454",
                "itemId":0,
                "type":"MT",
                "title":"<span class='colorOrange'>State Bank of India</span><br/><span class='bold'>Jyoti Ghosh</span>, General Manager of Commercial &amp;International Banking <span class='bold'><span class='colorBlue'>MOVED</span></span> to Chief General Manager of State Bank Of Hyderabad",
                "timestamp":"Wed, 16 May 2012 00:00:00 -0700",
                "isBookmarked":false},
            {"id":"MT:18139460",
                "itemId":0,
                "type":"MT",
                "title":"<span class='colorOrange'>State Bank of India</span><br/><span class='bold'>Jyoti Ghosh</span>, General Manager of Commercial &amp;International Banking <span class='bold'><span class='colorBlue'>MOVED</span></span> to Chief General Manager of State Bank Of Hyderabad",
                "timestamp":"Wed, 16 May 2012 00:00:00 -0700",
                "isBookmarked":false},
            {"id":"MT:17992325",
                "itemId":0,
                "type":"MT",
                "title":"<span class='colorOrange'>State Bank of India</span><br/><span class='bold'>Rajnish Kumar</span> <span class='bold'><span class='colorGreen'>JOINED</span></span> as Chief General Manager",
                "timestamp":"Fri, 27 Apr 2012 00:00:00 -0700",
                "isBookmarked":false},
            {"id":"MT:17797282",
                "itemId":0,
                "type":"MT",
                "title":"<span class='colorOrange'>Allahabad Bank</span><br/><span class='bold'>Tilak Raj Chawla</span> <span class='bold'><span class='colorGreen'>JOINED</span></span> as Executive Director",
                "timestamp":"Sun, 1 Apr 2012 00:00:00 -0700",
                "isBookmarked":false},
            {"id":"MT:17065028",
                "itemId":0,
                "type":"MT",
                "title":"<span class='colorOrange'>United Bank of India</span><br/><span class='bold'>M.V.Nair</span>, Managing Director <span class='bold'><span class='colorRed'>LEFT</span></span> ",
                "timestamp":"Sat, 31 Mar 2012 00:00:00 -0700",
                "isBookmarked":false},
            {"id":"MT:17787649",
                "itemId":0,
                "type":"MT",
                "title":"<span class='colorOrange'>Bank of India</span><br/><span class='bold'>Gauri Shankar</span> <span class='bold'><span class='colorGreen'>JOINED</span></span> as Chief Financial Officer",
                "timestamp":"Sat, 31 Mar 2012 00:00:00 -0700",
                "isBookmarked":false},
            {"id":"MT:17708938",
                "itemId":0,
                "type":"MT",
                "title":"<span class='colorOrange'>Kotak Mahindra Bank Limited</span><br/><span class='bold'>Shubham Majumder</span> <span class='bold'><span class='colorGreen'>JOINED</span></span> as Executive Director of Kotak Investment Banking",
                "timestamp":"Wed, 21 Mar 2012 00:00:00 -0700",
                "isBookmarked":false},
            {"id":"MT:17690367",
                "itemId":0,
                "type":"MT",
                "title":"<span class='colorOrange'>Housing Development Finance Corporation Limited</span><br/><span class='bold'>J. J. Irani</span>, Board of Directors <span class='bold'><span class='colorRed'>LEFT</span></span> ",
                "timestamp":"Mon, 19 Mar 2012 00:00:00 -0700",
                "isBookmarked":false},
            {"id":"MT:17629639",
                "itemId":0,
                "type":"MT",
                "title":"<span class='colorOrange'>YES BANK Limited</span><br/><span class='bold'>K Ramachandran</span> <span class='bold'><span class='colorGreen'>JOINED</span></span> as President of Investment Advisory &amp; Equity Research from Axis Bank Ltd.",
                "timestamp":"Fri, 9 Mar 2012 00:00:00 -0800",
                "isBookmarked":false},
            {"id":"MT:17629787",
                "itemId":0,
                "type":"MT",
                "title":"<span class='colorOrange'>YES BANK Limited</span><br/><span class='bold'>Chitra Pandeya</span> <span class='bold'><span class='colorGreen'>JOINED</span></span> as Senior President of Savings Liabilities Management, Cards &amp; Direct Banking from HDFC Bank Limited",
                "timestamp":"Fri, 9 Mar 2012 00:00:00 -0800",
                "isBookmarked":false},
            {"id":"MT:17065020",
                "itemId":0,
                "type":"MT",
                "title":"<span class='colorOrange'>United Bank of India</span><br/><span class='bold'>S L Bansal</span>, Executive Director <span class='bold'><span class='colorRed'>LEFT</span></span> for Oriental Bank of Commerce",
                "timestamp":"Thu, 1 Mar 2012 00:00:00 -0800",
                "isBookmarked":false},
            {"id":"MT:17065029",
                "itemId":0,
                "type":"MT",
                "title":"<span class='colorOrange'>Oriental Bank of Commerce</span><br/><span class='bold'>S L Bansal</span> <span class='bold'><span class='colorGreen'>JOINED</span></span> as Managing Director from United Bank of India",
                "timestamp":"Thu, 1 Mar 2012 00:00:00 -0800",
                "isBookmarked":false},
            {"id":"MT:17558400",
                "itemId":0,
                "type":"MT",
                "title":"<span class='colorOrange'>United Bank of India</span><br/><span class='bold'>D. Narang</span> <span class='bold'><span class='colorGreen'>JOINED</span></span> as Executive Director from Allahabad Bank",
                "timestamp":"Thu, 1 Mar 2012 00:00:00 -0800",
                "isBookmarked":false},
            {"id":"MT:17558487",
                "itemId":0,
                "type":"MT",
                "title":"<span class='colorOrange'>Allahabad Bank</span><br/><span class='bold'>D. Narang</span>, General Manager of Credit <span class='bold'><span class='colorRed'>LEFT</span></span> for United Bank of India",
                "timestamp":"Thu, 1 Mar 2012 00:00:00 -0800",
                "isBookmarked":false},
            {"id":"MT:17558489",
                "itemId":0,
                "type":"MT",
                "title":"<span class='colorOrange'>Karnataka Bank Ltd.</span><br/><span class='bold'>Meera Laetitia B Aranha</span>, Deputy General Manager <span class='bold'><span class='colorBlue'>MOVED</span></span> to General Manager",
                "timestamp":"Thu, 1 Mar 2012 00:00:00 -0800",
                "isBookmarked":false},
            {"id":"MT:17593395",
                "itemId":0,
                "type":"MT",
                "title":"<span class='colorOrange'>Karnataka Bank Ltd.</span><br/><span class='bold'>Chandrashekar Rao B.</span>, Assistant General Manager <span class='bold'><span class='colorBlue'>MOVED</span></span> to Deputy General Manager",
                "timestamp":"Thu, 1 Mar 2012 00:00:00 -0800",
                "isBookmarked":false},
            {"id":"MT:17065030",
                "itemId":0,
                "type":"MT",
                "title":"<span class='colorOrange'>Oriental Bank of Commerce</span><br/><span class='bold'>Nagesh Pydah</span>, Managing Director <span class='bold'><span class='colorRed'>LEFT</span></span> ",
                "timestamp":"Wed, 29 Feb 2012 00:00:00 -0800",
                "isBookmarked":false},
            {"id":"MT:17519067",
                "itemId":0,
                "type":"MT",
                "title":"<span class='colorOrange'>YES BANK Limited</span><br/><span class='bold'>Manpreet Singh Kochar</span> <span class='bold'><span class='colorGreen'>JOINED</span></span> as Executive Vice President from Kotak Mahindra Bank Limited",
                "timestamp":"Sat, 25 Feb 2012 00:00:00 -0800",
                "isBookmarked":false},
            {"id":"MT:17519098",
                "itemId":0,
                "type":"MT",
                "title":"<span class='colorOrange'>Kotak Mahindra Bank Limited</span><br/><span class='bold'>Manpreet Singh Kochar</span>, Vice President of Marketing - Retail Liabilities, Assets, NRI &amp; Branch Banking <span class='bold'><span class='colorRed'>LEFT</span></span> for YES BANK Limited",
                "timestamp":"Sat, 25 Feb 2012 00:00:00 -0800",
                "isBookmarked":false},
            {"id":"MT:17360953",
                "itemId":0,
                "type":"MT",
                "title":"<span class='colorOrange'>State Bank of Travancore</span><br/><span class='bold'>M. C. Jacob</span> <span class='bold'><span class='colorBlue'>MOVED</span></span> to Chief General Manager",
                "timestamp":"Mon, 6 Feb 2012 00:00:00 -0800",
                "isBookmarked":false},
            {"id":"MT:17204022",
                "itemId":0,
                "type":"MT",
                "title":"<span class='colorOrange'>Bank of Maharashtra Ltd.</span><br/><span class='bold'>Narendra Singh</span> <span class='bold'><span class='colorGreen'>JOINED</span></span> as Managing Director from Corporation Bank",
                "timestamp":"Wed, 1 Feb 2012 00:00:00 -0800",
                "isBookmarked":false},
            {"id":"MT:17312937",
                "itemId":0,
                "type":"MT",
                "title":"<span class='colorOrange'>ICICI Bank Limited</span><br/><span class='bold'>Swati Piramal</span> <span class='bold'><span class='colorGreen'>JOINED</span></span> as Board of Directors",
                "timestamp":"Tue, 31 Jan 2012 00:00:00 -0800",
                "isBookmarked":false},
            {"id":"MT:17230180",
                "itemId":0,
                "type":"MT",
                "title":"<span class='colorOrange'>HDFC Bank Limited</span><br/><span class='bold'>Keki Mistry</span> <span class='bold'><span class='colorGreen'>JOINED</span></span> as Board of Directors",
                "timestamp":"Thu, 19 Jan 2012 00:00:00 -0800",
                "isBookmarked":false},
            {"id":"MT:17065023",
                "itemId":0,
                "type":"MT",
                "title":"<span class='colorOrange'>Bank of India</span><br/><span class='bold'>M S Raghavan</span> <span class='bold'><span class='colorGreen'>JOINED</span></span> as Executive Director from Indian Overseas Bank",
                "timestamp":"Sun, 1 Jan 2012 00:00:00 -0800",
                "isBookmarked":false},
            {"id":"MT:17065067",
                "itemId":0,
                "type":"MT",
                "title":"<span class='colorOrange'>Andhra Bank</span><br/><span class='bold'>Raj Kumar</span>, General Manager <span class='bold'><span class='colorRed'>LEFT</span></span> for Indian Bank",
                "timestamp":"Sun, 1 Jan 2012 00:00:00 -0800",
                "isBookmarked":false},
            {"id":"MT:17065068",
                "itemId":0,
                "type":"MT",
                "title":"<span class='colorOrange'>Indian Overseas Bank</span><br/><span class='bold'>M S Raghavan</span>, General Manager <span class='bold'><span class='colorRed'>LEFT</span></span> for Bank of India",
                "timestamp":"Sun, 1 Jan 2012 00:00:00 -0800",
                "isBookmarked":false},
            {"id":"MT:17085959",
                "itemId":0,
                "type":"MT",
                "title":"<span class='colorOrange'>Indian Overseas Bank</span><br/><span class='bold'>A D .M Chavali</span> <span class='bold'><span class='colorGreen'>JOINED</span></span> as Executive Director from Bank of Baroda",
                "timestamp":"Sat, 31 Dec 2011 00:00:00 -0800",
                "isBookmarked":false},
            {"id":"MT:17086015",
                "itemId":0,
                "type":"MT",
                "title":"<span class='colorOrange'>Bank of Baroda</span><br/><span class='bold'>A D .M Chavali</span>, General Manager <span class='bold'><span class='colorRed'>LEFT</span></span> for Indian Overseas Bank",
                "timestamp":"Sat, 31 Dec 2011 00:00:00 -0800",
                "isBookmarked":false},
            {"id":"MT:17078725",
                "itemId":0,
                "type":"MT",
                "title":"<span class='colorOrange'>Karur Vysya Bank</span><br/><span class='bold'>Krishna Kumar</span>, Board of Directors <span class='bold'><span class='colorRed'>LEFT</span></span> ",
                "timestamp":"Thu, 29 Dec 2011 00:00:00 -0800",
                "isBookmarked":false}
        ],
        "monitor":{"id":"M:67657",
            "type":"PRIVATE",
            "title":"Indian Banks",
            "timestamp":"Mon, 26 Dec 2011 01:28:43 -0800",
            "hasNew":false,
            "hasNewMail":false,
            "hasMail":true,
            "hasChart":true,
            "favorite":false,
            "isAdmin":false}},
    "status":"SUCCESS"}